[package]
name = "glhserializer"
version = "0.4.2"
edition = "2021"
description = "Fast, compact binary serialization for structured data. Originally built for Glyph, usable anywhere."
license = "MIT"
repository = "https://github.com/JasonKenwayFJ/GLHSerializer"
readme = "readme.md"

[lib]
name = "glh"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
